FROM eclipse-temurin:21-jdk AS build

WORKDIR /app

COPY . .

RUN chmod +x mvnw
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/task-management-system-0.0.1-SNAPSHOT.jar app.jar

COPY start.sh start.sh

RUN chmod +x start.sh

EXPOSE 8080

ENTRYPOINT ["./start.sh"]